# Generated by Django 4.2.4 on 2023-10-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="is_current_period",
            field=models.BooleanField(default=False),
        ),
    ]
